Core:
  plugin:
    language: en
    debugmode: false
    usagestats: true
  language:
    default: English
    serverforced: false
    playerset: true
  translate:
    internal: true
    manual: true
  welcome:
    delay: 2 seconds
    show: 10 seconds
  geoip:
    enabled: true
