plugin:
  language:
    commands: English                              # Language you want to use for commands that matches a directory under translations.
    messages: English                              # Language you want to use for messages that matches a directory under translations.
  debugmode: false                                 # Enable/disable debugging mode and additional console output.
  usagestats: true                                 # Enable/disable usage stats reporting to CraftFire devs.
  logging: true                                    # Enable/disable logging to files.
  logformat: yyyy-MM-dd                            # Filename format of the AuthDB debug and error log files.
language:
  default: English                                 # 
  serverforced: false                              # 
  playerset: true                                  # 
#translate:
#  internal: true                                   # 
#  manual: true                                     # 
#welcome:
#  delay: 2 seconds                                 # 
#  show: 10 seconds                                 # 
#geoip:
#  enabled: true                                    # 
#  autoupdate: true                                 # 
